Repository BME-MIT-IET/iet-hf2021-snek, pull requests merged in 2021-05, with the labels that each got.

#13 Bdd branch
  requirements.txt
  tests/bdd/features/search.feature
  tests/bdd/features/sort.feature
  tests/bdd/features/steps/steps.py
Labels: BDD

#17 Szacsi benchmark 2
  doc/doc_exercise_3.md
  doc/img.png
  doc/img_1.png
  requirements.txt
  tests/Benchmark.py
  tests/Benchmark/Benchmark.py
  tests/Benchmark/Plots/fast_algo_runs_2.png
  tests/Benchmark/Plots/slow_algo_runs.png
Labels: Nem-funkcionális

#15 Laci's unit tests
  algorithms/maths/diffie_hellman_key_exchange.py
  algorithms/maths/euler_totient.py
  algorithms/maths/find_primitive_root_simple.py
  algorithms/matrix/sparse_dot_vector.py
  doc/doc_exercise_2.md
  tests/test_maths.py
  tests/test_matrix.py
Labels: Egység tesztelés coverage

#16 Szuki unit tests
  algorithms/dp/max_product_subarray.py
  algorithms/dp/regex_matching.py
  algorithms/heap/__init__.py
  algorithms/linkedlist/__init__.py
  algorithms/linkedlist/merge_sorted_k_lists.py
  doc/doc_exercise_2.md
  tests/test_bfs.py
  tests/test_dp.py
  tests/test_graph.py
  tests/test_heap.py
  tests/test_linkedlist.py
Labels: Egység tesztelés coverage

#20 Bence's unit tests
  tests/test_is_consecutive.py
Labels: Egység tesztelés coverage

#21 BDD dokumentáció hozzáadása
  doc/doc_exercise_4.md
Labels: documentation
